################################################################################
#                           PROJECT INFORMATION                                #
#                              Name: MUTADOCK                                  #
#                           Author: Naisarg Patel                              #
#                                                                              #
#       Copyright (C) 2026 Naisarg Patel (https://github.com/naisarg14)        #
#                                                                              #
#          Project: https://github.com/naisarg14/mutadock                      #
#                                                                              #
#   This program is free software; you can redistribute it and/or modify it    #
#  under the terms of the GNU General Public License version 3 as published    #
#  by the Free Software Foundation.                                            #
#                                                                              #
#  This program is distributed in the hope that it will be useful, but         #
#  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY  #
#  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License    #
#  for more details.                                                           #
################################################################################
"""PowerPoint (``.pptx``) report generator for MUTADOCK runs.

This module renders a presentation-grade slide deck a PI can present, reusing
the *exact same* chart images produced for the HTML report. It builds only on
the shared :mod:`mutadock.report.data` contract (:class:`RunData`,
:func:`summary_stats`, :func:`mutation_label`) and consumes figures that were
pre-generated by :mod:`mutadock.report.figures` and handed in as a dict of
base64 PNG strings (any value may be ``None`` to skip that image/slide).

The public entry point, :func:`build_pptx`, returns an in-memory
``pptx.presentation.Presentation`` object; the caller is responsible for
``prs.save(path)``. Keeping I/O out of here makes the deck fully testable.
"""

from __future__ import annotations

import base64
import io

from pptx import Presentation as _new_presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.presentation import Presentation
from pptx.util import Emu, Inches, Pt

from .data import RunData, mutation_label, summary_stats

try:  # Pillow is available in the project env; used only for aspect ratio.
    from PIL import Image

    _HAVE_PIL = True
except Exception:  # pragma: no cover - graceful fallback
    _HAVE_PIL = False


# ---------------------------------------------------------------------------
# Palette (mirrors the dataviz standard used by figures.py)
# ---------------------------------------------------------------------------
_INK_PRIMARY = RGBColor(0x0B, 0x0B, 0x0B)
_INK_SECONDARY = RGBColor(0x52, 0x51, 0x4E)
_BLUE = RGBColor(0x2A, 0x78, 0xD6)
_SURFACE = RGBColor(0xFC, 0xFC, 0xFB)
_TABLE_HEADER_BG = RGBColor(0x2A, 0x78, 0xD6)
_TABLE_HEADER_FG = RGBColor(0xFF, 0xFF, 0xFF)
_TABLE_ROW_BG = RGBColor(0xF3, 0xF4, 0xF6)
_TABLE_ROW_ALT_BG = RGBColor(0xFC, 0xFC, 0xFB)

_FONT = "Calibri"

# 16:9 canvas.
_SLIDE_W = Inches(13.333)
_SLIDE_H = Inches(7.5)

# Consistent content geometry.
_DEFAULT_ROW_H = Inches(0.34)
_MARGIN = Inches(0.7)
_TITLE_TOP = Inches(0.35)
_TITLE_H = Inches(0.9)
_BODY_TOP = Inches(1.35)


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------
def _b64_to_stream(b64: str) -> io.BytesIO:
    """Turn a base64 PNG string into a fresh BytesIO positioned at 0."""
    stream = io.BytesIO(base64.b64decode(b64))
    stream.seek(0)
    return stream


def _blank_slide(prs: Presentation):
    """Add and return a slide using the blank layout (index 6)."""
    return prs.slides.add_slide(prs.slide_layouts[6])


def _set_run(
    run,
    text: str,
    *,
    size: int,
    bold: bool = False,
    color: RGBColor = _INK_PRIMARY,
) -> None:
    """Apply text + font styling to a run."""
    run.text = text
    font = run.font
    font.name = _FONT
    font.size = Pt(size)
    font.bold = bold
    font.color.rgb = color


def _add_textbox(
    slide,
    left,
    top,
    width,
    height,
    text: str,
    *,
    size: int,
    bold: bool = False,
    color: RGBColor = _INK_PRIMARY,
    align=PP_ALIGN.LEFT,
    anchor=MSO_ANCHOR.TOP,
):
    """Add a single-paragraph textbox and return the shape."""
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    para = tf.paragraphs[0]
    para.alignment = align
    _set_run(para.add_run(), text, size=size, bold=bold, color=color)
    return box


def _add_title(slide, text: str) -> None:
    """Add a consistent slide title with a thin blue accent underline."""
    _add_textbox(
        slide,
        _MARGIN,
        _TITLE_TOP,
        _SLIDE_W - 2 * _MARGIN,
        _TITLE_H,
        text,
        size=30,
        bold=True,
        color=_INK_PRIMARY,
        anchor=MSO_ANCHOR.MIDDLE,
    )
    # Accent underline just below the title text.
    line = slide.shapes.add_textbox(
        _MARGIN,
        _TITLE_TOP + _TITLE_H - Inches(0.12),
        Inches(1.8),
        Inches(0.06),
    )
    line.fill.solid()
    line.fill.fore_color.rgb = _BLUE
    line.line.fill.background()


def _picture_box(
    slide,
    b64: str,
    box_left,
    box_top,
    box_w,
    box_h,
) -> None:
    """Center a base64 PNG within the given box, preserving aspect ratio."""
    stream = _b64_to_stream(b64)

    aspect = None
    if _HAVE_PIL:
        try:
            with Image.open(stream) as img:
                w_px, h_px = img.size
            if w_px and h_px:
                aspect = h_px / w_px
        except Exception:
            aspect = None
        stream.seek(0)

    box_w_emu = int(box_w)
    box_h_emu = int(box_h)

    if aspect is not None:
        # Fit within the box (contain), preserving aspect.
        width = min(box_w_emu, int(box_h_emu / aspect))
        height = int(width * aspect)
        left = int(box_left) + (box_w_emu - width) // 2
        top = int(box_top) + (box_h_emu - height) // 2
        slide.shapes.add_picture(
            stream, Emu(left), Emu(top), width=Emu(width), height=Emu(height)
        )
    else:
        # No PIL: fall back to width-only; pptx keeps aspect.
        pic = slide.shapes.add_picture(
            stream, Emu(int(box_left)), Emu(int(box_top)), width=Emu(box_w_emu)
        )
        # Best-effort horizontal/vertical centering after the fact.
        pic.left = Emu(int(box_left) + (box_w_emu - pic.width) // 2)
        pic.top = Emu(int(box_top) + max(0, (box_h_emu - pic.height) // 2))


def _style_cell(
    cell,
    text: str,
    *,
    size: int,
    bold: bool = False,
    color: RGBColor = _INK_PRIMARY,
    bg: RGBColor | None = None,
    align=PP_ALIGN.LEFT,
) -> None:
    """Set a table cell's text, font and fill."""
    cell.vertical_anchor = MSO_ANCHOR.MIDDLE
    cell.margin_left = Inches(0.08)
    cell.margin_right = Inches(0.08)
    cell.margin_top = Inches(0.02)
    cell.margin_bottom = Inches(0.02)
    if bg is not None:
        cell.fill.solid()
        cell.fill.fore_color.rgb = bg
    tf = cell.text_frame
    tf.word_wrap = True
    para = tf.paragraphs[0]
    para.alignment = align
    _set_run(para.add_run(), text, size=size, bold=bold, color=color)


def _add_table(
    slide,
    header: list[str],
    rows: list[list[str]],
    left,
    top,
    width,
    *,
    col_aligns: list | None = None,
    font_size: int = 13,
    row_height=_DEFAULT_ROW_H,
):
    """Add a styled native PPTX table and return the GraphicFrame."""
    n_rows = len(rows) + 1
    n_cols = len(header)
    height = Emu(int(row_height) * n_rows)
    gfx = slide.shapes.add_table(n_rows, n_cols, left, top, width, height)
    table = gfx.table
    if col_aligns is None:
        col_aligns = [PP_ALIGN.LEFT] * n_cols

    for c, name in enumerate(header):
        _style_cell(
            table.cell(0, c),
            name,
            size=font_size,
            bold=True,
            color=_TABLE_HEADER_FG,
            bg=_TABLE_HEADER_BG,
            align=col_aligns[c],
        )
    for r, row in enumerate(rows, start=1):
        bg = _TABLE_ROW_BG if r % 2 else _TABLE_ROW_ALT_BG
        for c, value in enumerate(row):
            _style_cell(
                table.cell(r, c),
                value,
                size=font_size,
                color=_INK_PRIMARY,
                bg=bg,
                align=col_aligns[c],
            )
    return gfx


def _fmt(value, spec: str = "") -> str:
    """Format a possibly-None numeric value, returning '-' for None."""
    if value is None:
        return "-"
    if spec:
        try:
            return format(value, spec)
        except (ValueError, TypeError):
            return str(value)
    return str(value)


# ---------------------------------------------------------------------------
# Slide builders
# ---------------------------------------------------------------------------
def _slide_title(prs: Presentation, run: RunData, title: str) -> None:
    slide = _blank_slide(prs)
    _add_textbox(
        slide,
        _MARGIN,
        Inches(2.6),
        _SLIDE_W - 2 * _MARGIN,
        Inches(1.4),
        title,
        size=44,
        bold=True,
        color=_INK_PRIMARY,
        anchor=MSO_ANCHOR.MIDDLE,
    )
    # Accent bar.
    bar = slide.shapes.add_textbox(_MARGIN, Inches(4.0), Inches(3.0), Inches(0.08))
    bar.fill.solid()
    bar.fill.fore_color.rgb = _BLUE
    bar.line.fill.background()

    input_name = run.metadata.get("input") or (
        str(run.input_pdb) if run.input_pdb is not None else "n/a"
    )
    generated = run.metadata.get("generated_at", "")
    subtitle = f"Input: {input_name}"
    if generated:
        subtitle += f"    •    Generated: {generated}"
    _add_textbox(
        slide,
        _MARGIN,
        Inches(4.3),
        _SLIDE_W - 2 * _MARGIN,
        Inches(1.0),
        subtitle,
        size=18,
        color=_INK_SECONDARY,
    )


def _slide_summary(prs: Presentation, run: RunData) -> None:
    slide = _blank_slide(prs)
    _add_title(slide, "Run summary")
    stats = summary_stats(run)

    rows: list[list[str]] = []
    rows.append(["Mutations scored", str(stats["n_scored"])])
    rows.append(["Stabilizing (ΔΔG < 0)", str(stats["n_stabilizing"])])
    if stats["best_ddg"] is not None:
        label = stats["best_ddg_label"] or ""
        value = f"{stats['best_ddg']:.2f} REU"
        if label:
            value += f"  ({label})"
        rows.append(["Best ΔΔG", value])
    if stats["n_docked"]:
        rows.append(["Docked", str(stats["n_docked"])])
    if stats["best_affinity"] is not None:
        name = stats["best_affinity_name"] or ""
        value = f"{stats['best_affinity']:.2f} kcal/mol"
        if name:
            value += f"  ({name})"
        rows.append(["Best affinity", value])

    _add_table(
        slide,
        ["Metric", "Value"],
        rows,
        _MARGIN,
        _BODY_TOP + Inches(0.3),
        Inches(9.5),
        col_aligns=[PP_ALIGN.LEFT, PP_ALIGN.LEFT],
        font_size=16,
        row_height=Inches(0.55),
    )


def _slide_ddg(prs: Presentation, b64: str) -> None:
    slide = _blank_slide(prs)
    _add_title(slide, "ΔΔG distribution")
    _picture_box(
        slide,
        b64,
        _MARGIN,
        _BODY_TOP,
        _SLIDE_W - 2 * _MARGIN,
        _SLIDE_H - _BODY_TOP - Inches(0.4),
    )


def _slide_top_mutations(
    prs: Presentation, run: RunData, b64: str | None, top_n: int
) -> None:
    slide = _blank_slide(prs)
    _add_title(slide, "Top stabilizing mutations")

    single_df = run.single_df
    have_table = single_df is not None and len(single_df) > 0

    content_top = _BODY_TOP
    content_h = _SLIDE_H - content_top - Inches(0.4)

    if b64 is not None and have_table:
        # Image on the left half, table on the right half.
        half_w = (_SLIDE_W - 2 * _MARGIN - Inches(0.3)) / 2
        _picture_box(slide, b64, _MARGIN, content_top, Emu(int(half_w)), content_h)
        table_left = Emu(int(_MARGIN) + int(half_w) + int(Inches(0.3)))
        _add_mutation_table(
            slide, single_df, top_n, table_left, content_top, Emu(int(half_w))
        )
    elif b64 is not None:
        _picture_box(
            slide, b64, _MARGIN, content_top, _SLIDE_W - 2 * _MARGIN, content_h
        )
    elif have_table:
        _add_mutation_table(slide, single_df, top_n, _MARGIN, content_top, Inches(7.0))


def _add_mutation_table(slide, single_df, top_n, left, top, width) -> None:
    """Build the Rank | Mutation | ΔΔG table of the top single rows."""
    k = min(int(top_n), 10)
    records = single_df.head(k).to_dict("records")
    rows: list[list[str]] = []
    for i, rec in enumerate(records, start=1):
        ddg = rec.get("ddG_value")
        try:
            ddg_str = f"{float(ddg):.2f}"
        except (ValueError, TypeError):
            ddg_str = str(ddg)
        rows.append([str(i), mutation_label(rec), ddg_str])
    _add_table(
        slide,
        ["Rank", "Mutation", "ΔΔG (REU)"],
        rows,
        left,
        top,
        width,
        col_aligns=[PP_ALIGN.CENTER, PP_ALIGN.LEFT, PP_ALIGN.RIGHT],
        font_size=12,
        row_height=Inches(0.32),
    )


def _slide_docking(prs: Presentation, run: RunData, b64: str | None) -> None:
    slide = _blank_slide(prs)
    _add_title(slide, "Docking affinity")

    docking_df = run.docking_df
    content_top = _BODY_TOP
    content_h = _SLIDE_H - content_top - Inches(0.4)

    if b64 is not None:
        half_w = (_SLIDE_W - 2 * _MARGIN - Inches(0.3)) / 2
        _picture_box(slide, b64, _MARGIN, content_top, Emu(int(half_w)), content_h)
        table_left = Emu(int(_MARGIN) + int(half_w) + int(Inches(0.3)))
        _add_docking_table(slide, docking_df, table_left, content_top, Emu(int(half_w)))
    else:
        _add_docking_table(slide, docking_df, _MARGIN, content_top, Inches(7.0))


def _add_docking_table(slide, docking_df, left, top, width) -> None:
    """Build the Name | Affinity table of the top docking rows."""
    records = docking_df.head(10).to_dict("records")
    rows: list[list[str]] = []
    for rec in records:
        name = str(rec.get("name", ""))
        if name.endswith("_Ligand"):
            name = name[: -len("_Ligand")]
        aff = rec.get("affinity")
        try:
            aff_str = f"{float(aff):.2f}"
        except (ValueError, TypeError):
            aff_str = str(aff)
        rows.append([name, aff_str])
    _add_table(
        slide,
        ["Name", "Affinity (kcal/mol)"],
        rows,
        left,
        top,
        width,
        col_aligns=[PP_ALIGN.LEFT, PP_ALIGN.RIGHT],
        font_size=12,
        row_height=Inches(0.32),
    )


def _slide_structure(prs: Presentation, run: RunData, b64: str) -> None:
    slide = _blank_slide(prs)
    _add_title(slide, "Top mutant structure")

    stats = summary_stats(run)
    caption = stats.get("best_ddg_label")

    caption_h = Inches(0.5) if caption else Inches(0.0)
    content_top = _BODY_TOP
    content_h = _SLIDE_H - content_top - Inches(0.4) - caption_h
    _picture_box(slide, b64, _MARGIN, content_top, _SLIDE_W - 2 * _MARGIN, content_h)
    if caption:
        _add_textbox(
            slide,
            _MARGIN,
            _SLIDE_H - Inches(0.4) - caption_h,
            _SLIDE_W - 2 * _MARGIN,
            caption_h,
            f"Mutation: {caption}",
            size=15,
            color=_INK_SECONDARY,
            align=PP_ALIGN.CENTER,
        )


def _slide_provenance(prs: Presentation, run: RunData) -> None:
    slide = _blank_slide(prs)
    _add_title(slide, "Provenance & methods")

    meta = run.metadata
    versions = meta.get("versions", {}) or {}
    rows: list[list[str]] = [
        ["Generated at", str(meta.get("generated_at", "-"))],
        ["Input", str(meta.get("input", "-"))],
        ["Output directory", str(meta.get("output_dir", "-"))],
        ["PyRosetta", str(versions.get("pyrosetta", "-"))],
        ["Vina", str(versions.get("vina", "-"))],
    ]
    files = meta.get("files", []) or []
    if files:
        rows.append(["Source files", ", ".join(str(f) for f in files)])

    _add_table(
        slide,
        ["Field", "Value"],
        rows,
        _MARGIN,
        _BODY_TOP,
        _SLIDE_W - 2 * _MARGIN,
        col_aligns=[PP_ALIGN.LEFT, PP_ALIGN.LEFT],
        font_size=11,
        row_height=Inches(0.5),
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def build_pptx(
    run: RunData,
    figures: dict,
    *,
    top_n: int = 15,
    title: str | None = None,
) -> Presentation:
    """Build a presentation-grade slide deck for a MUTADOCK run.

    Args:
        run: A loaded :class:`RunData` (see :func:`mutadock.report.data.discover_run`).
        figures: Pre-generated base64 PNG strings keyed by
            ``"ddg_distribution"``, ``"top_mutations"``, ``"affinity"`` and
            ``"structure"``. Any value may be ``None`` to skip its image/slide.
        top_n: Maximum number of top single mutations to tabulate (capped at 10
            in the table for legibility).
        title: Title-slide heading. Defaults to
            ``f"MUTADOCK Report — {run.base_name}"``.

    Returns:
        An in-memory ``pptx.presentation.Presentation``. The caller saves it.
    """
    if title is None:
        title = f"MUTADOCK Report — {run.base_name}"

    prs = _new_presentation()
    prs.slide_width = _SLIDE_W
    prs.slide_height = _SLIDE_H

    # 1. Title (always).
    _slide_title(prs, run, title)

    # 2. Run summary (always).
    _slide_summary(prs, run)

    # 3. ΔΔG distribution (if figure present).
    if figures.get("ddg_distribution"):
        _slide_ddg(prs, figures["ddg_distribution"])

    # 4. Top stabilizing mutations (table if single_df, image if figure).
    if run.single_df is not None or figures.get("top_mutations"):
        _slide_top_mutations(prs, run, figures.get("top_mutations"), top_n)

    # 5. Docking affinity (if docking data present).
    if run.docking_df is not None:
        _slide_docking(prs, run, figures.get("affinity"))

    # 6. Top mutant structure (if figure present).
    if figures.get("structure"):
        _slide_structure(prs, run, figures["structure"])

    # 7. Provenance / methods (always).
    _slide_provenance(prs, run)

    return prs
